### ISSUE TITLE
errors when running tests 

### ISSUE THREAD

**Issue by MengjieSHI** [BohndiekLab/patato#26]
Hi @tomelse, 

I tested the option 1: using pip to install PATATO and tried to run tests. It seems the 'tests' folder is not downloaded, so I manually added it. The test failed because of three errors. I attached the screenshot of the error below. 

![image](https://github.com/BohndiekLab/patato/assets/59768848/bebff889-eb61-4fea-9aaa-0489f4ca5f68)

The last two errors seem caused by the missing files due to the default relative path. Any suggestions to fix these?

**Comment by tomelse** [comment]
Hi @MengjieSHI,
Thanks so much for taking the time to review the code.

The layout of the package means that the tests have to be run on a locally installed version of PATATO. The way I've done this usually is the following:

```
git clone https://github.com/BohndiekLab/patato 
cd patato
pip install -e .
cd tests
python -m unittest
```

This means that we don't have to ship all of the test code and example data with the installable version, reducing the amount of download time required for installing PATATO. 

I hope that's okay? I tested it on Google Colab, and it seems to work. 

Thanks,
Tom

**Comment by MengjieSHI** [comment]
Thanks for your fast response! Tests were running without issues now. 

A minor comment on the [documentation](https://patato.readthedocs.io/en/latest/intro/03b_example_data.html) page, I guess you forgot to update the file names included in the example. I replaced them with'invivo_oe.hdf5' and 'invivo_dce.hdf5' and it works perfectly.
