### ISSUE TITLE
Minor comments 

### ISSUE THREAD

**Issue by MengjieSHI** [BohndiekLab/patato#34]
Hi @tomelse,  I am running the examples, and they work perfectly:)  Here are some minor comments I have for further improvements. 

1. I guess the folder named study contains the folder named Scan_1, Scan_2. It would be great to rephrase the explanations a bit, as the files were also named Scan_1. 

`patato-import-ithera /path/to/ithera/study/folder /path/to/data/folder`

2. For the GUI of tuning the speed-of-sound, 
a. The captions of the subfigures were missing. Did the right figure show the profile along x or z direction? 
b. Is it possible to reopen the GUI using the same command after I saved the speed-of-sound and quit it?  I failed on this, but I am wondering if there is a need to modify the speed-of-sound afterwards. 

3. I am not very clear about how to rename the ROIs on the GUI. I clicked the rename button, but it seems it didn't work as expected. 

4. A link is missing at line 3, first para, Examples 4. Figures got overlapping in the results of Block [10]. 

Thanks! 

This is part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/5686#issuecomment-1726350602)

**Comment by tomelse** [comment]
Glad to hear the examples run perfectly! And apologies for the delayed response. 

Could you elaborate a bit what you mean for part 1? Do you mean clarify in the Quick start guide in the documentation?

I've updated both the GUIs for ROI drawing and speed of sound tuning. I've wanted to update them for a long time... I've removed the line plot functionality as I don't think it's that helpful. Feel free to try it out and let me know if there's anything you think I've missed. 

The same commands can still be used, but with no arguments this time.

```bash
patato-set-speed-of-sound
patato-draw-roi
```

I will work on number 4 today.

Thanks very much!

**Comment by tomelse** [comment]
@MengjieSHI I've now fixed all of the issues you mentioned (see here: [https://patato.readthedocs.io/en/latest/examples/04_timeseriesanalysis.html](https://patato.readthedocs.io/en/latest/examples/04_timeseriesanalysis.html)).

**Comment by MengjieSHI** [comment]
Hi @tomelse Thanks for your updates! Yes, I mean it would be better to clarify a bit for Part 1 as the folder and files have the same name in your example. 

I downloaded the latest release 0.5.12 from GitHub but seems the updates on GUIs were not applied, either for the commands. It is quite wired, anything you think I could try? Thanks!

**Comment by tomelse** [comment]
Have you run 

`pip install --upgrade patato`

or `pip install --upgrade -e .`

to install the updated version?

**Comment by MengjieSHI** [comment]
Yes, just restarted my computer and everything works well now:) 

The new GUIs look really great!

It seems there is no return after I clicked save speed of sound? I also got some warnings after closing the GUI. 
![image](https://github.com/BohndiekLab/patato/assets/59768848/9ec46247-98d5-46d3-b0a4-e84c4802b811)
