### ISSUE TITLE
Speed of sound using command line

### ISSUE THREAD

**Issue by ASK-DataScience** [BohndiekLab/patato#40]
Hi @tomelse,

I tried to run the command: patato-set-speed-of-sound

It showed the GUI and the example data and I could change the value. However the output shows this:

![image](https://github.com/BohndiekLab/patato/assets/7422503/c5c31a4b-e076-4b27-82e8-d0cb5589d339)

**Comment by tomelse** [comment]
Does the GUI work as expected? I think the errors/warnings come from tkinter, the toolkit used for making the GUI and shouldn't affect the functioning of the program.

**Comment by ASK-DataScience** [comment]
Yes, the GUI works as expected.
