### ISSUE TITLE
Errors while running tests

### ISSUE THREAD

**Issue by ASK-DataScience** [BohndiekLab/patato#41]
I am getting an error after running this step: pip install -e .

![image](https://github.com/BohndiekLab/patato/assets/7422503/96b1991b-037f-42db-9835-1e53dd095dd3)

Also after running this step: python -m unittest

![image](https://github.com/BohndiekLab/patato/assets/7422503/fa807f61-24e1-442e-b6e2-af523078da8c)

This is part of JOSS [Review](https://github.com/openjournals/joss-reviews/issues/5686)

**Comment by tomelse** [comment]
The error with editable install is because Python requires the bundled C++ code to be compiled using Microsoft c++ build tools. 

My intention for the unittests was to run the tests as follows. That way you don't need the compiler. I haven't worked out a good way of distributing the unittests through pip, so this seemed like the most sensible way to do it, given that most people won't be running unittests (unless you have any other suggestions?). 

```
pip install patato
git clone https://github.com/BohndiekLab/patato
cd patato/tests
python -m unittest
```

**Comment by tomelse** [comment]
P.s. I don't really recognise the ImportError that you get in your second screenshot, so please let me know if this doesn't solve the problems :)

**Comment by tomelse** [comment]
@ASK-DataScience do you think this is an acceptable way to do this?

**Comment by ASK-DataScience** [comment]
@tomelse I agree with you that most people won't be running unittests, but as a reviewer I should check if it is working correctly for me. Any suggestion on how to make it work? I followed your steps in the documentation.

**Comment by tomelse** [comment]
Did you try the instructions in my previous comment? I.e. installing but not editable (pip install patato), then separately git checkout the repo and run the tests on that code

**Comment by tomelse** [comment]
Otherwise you'd need to install the Microsoft C++ tools to compile the internal C++ code used for one of the algorithms

**Comment by ASK-DataScience** [comment]
@tomelse I just tried the instructions in your previous comment (not editable) and I got the following error:

![image](https://github.com/BohndiekLab/patato/assets/7422503/3410a992-3f62-4eed-abd1-8f456f221cec)

**Comment by ASK-DataScience** [comment]
So looks like the first error is resolved, but we are still stuck with the second one.

**Comment by tomelse** [comment]
What version of Python are you using?

**Comment by ASK-DataScience** [comment]
patato is imported but still cannot run unittest

![image](https://github.com/BohndiekLab/patato/assets/7422503/bb889729-256c-4f5b-b0cf-969ae451acc2)

**Comment by ASK-DataScience** [comment]
OK. Tests are finally working for me. But I had to install and run patato on the "base" environment instead of its own environment.

![image](https://github.com/BohndiekLab/patato/assets/7422503/b2e61a70-1c4f-4a33-9ef8-180ed4dfbd5b)

**Comment by ASK-DataScience** [comment]
I suggest you add the option to run patato as not editable on the documentation page as well.

**Comment by tomelse** [comment]
Thanks, I'll add that to the documentation.
